{
 "title": "Website monitoring (G7)",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "target", "label": "target", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Probe duration / HTTP status code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=\"$target\",job=\"website-monitoring-http\"}",
     "legendFormat": "duration"
    },
    {
     "expr": "probe_http_status_code{instance=\"$target\"} == 200",
     "legendFormat": "status code"
    },
    {
     "expr": "probe_http_status_code{instance=\"$target\"} != 200",
     "legendFormat": "invalid status code"
    }
   ]
  },
  {
   "title": "probe_icmp_duration_seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{instance=\"$target\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "probe_http_duration_seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=\"$target\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  }
 ]
}