{
 "title": "Website monitoring (Grafana 6+)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "target", "label": "target", "query": "label_values(instance)" },
   { "name": "http_job", "query": "${VAR_HTTP_JOB}" },
   { "name": "icmp_job", "query": "${VAR_ICMP_JOB}" }
  ]
 },
 "panels": [
  {
   "title": "HTTP status code",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"$http_job\",instance=\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP redirects",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_redirects{job=\"$http_job\",instance=\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_version{job=\"$http_job\",instance=\"$target\"}"
    }
   ]
  },
  {
   "title": "DNS lookup time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{job=\"$http_job\",instance=\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_ssl{job=\"$http_job\",instance=\"$target\"}"
    }
   ]
  },
  {
   "title": "Certificate validity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(probe_ssl_earliest_cert_expiry{job=\"$http_job\",instance=\"$target\"} - time()) / (60*60*24)"
    }
   ]
  },
  {
   "title": "TLS version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_tls_version_info{job=\"$http_job\",instance=\"$target\"}"
    }
   ]
  },
  {
   "title": "ICMP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{job=\"$icmp_job\",instance=\"$target\"}"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(probe_success{job=\"$http_job\",instance=~\"$target\"}[$__interval]) * 100"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(probe_success{job=\"$http_job\",instance=~\"$target\"}[$__interval]) * 100"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(probe_success{job=\"$http_job\",instance=~\"$target\"}[$__interval]) * 100"
    }
   ]
  },
  {
   "title": "HTTP probe duration / status code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"$http_job\",instance=\"$target\"}",
     "legendFormat": "duration"
    },
    {
     "expr": "probe_http_status_code{job=\"$http_job\",instance=\"$target\"} != 200",
     "legendFormat": "bad status code"
    },
    {
     "expr": "probe_http_status_code{job=\"$http_job\",instance=\"$target\"} == 200",
     "legendFormat": "status code"
    }
   ]
  },
  {
   "title": "ICMP probe duration / failure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"$icmp_job\",instance=\"$target\"}",
     "legendFormat": "duration"
    },
    {
     "expr": "probe_success{job=\"$icmp_job\",instance=\"$target\"} == 0",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "HTTP probe duration (by phase)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{job=\"$http_job\",instance=\"$target\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "ICMP probe duration (by phase)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{job=\"$icmp_job\",instance=\"$target\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  }
 ]
}